# coding: utf-8

"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dm_api_account.models.bb_parse_mode import BbParseMode

class TestBbParseMode(unittest.TestCase):
    """BbParseMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBbParseMode(self):
        """Test BbParseMode"""
        # inst = BbParseMode()

if __name__ == '__main__':
    unittest.main()
